pipeline_template: examples/dynamic/Jenkinsfile
some_config: imaconfigvalue
docker_container: python:3.6-stretch
agent_label: some-other-label
script_to_run: |-
  pip install pipenv
  export PATH=$(python -m site --user-base)/bin:$PATH
  pipenv install --system
  pytest
