pipeline_template: examples/python/Jenkinsfile
some_config: imaconfigvalue
script_to_run: |-
  pip install --user pipenv
  pipenv install
  export VENV_HOME_DIR=$(pipenv --venv)
  source ${VENV_HOME_DIR}/bin/activate
  pipenv run pytest --capture=no --ds=config.settings.test --flake8 .
