pipeline_template: examples/python/Jenkinsfile
some_config: imaconfigvalue
script_to_run: |-
  pip install --user pipenv
  export PATH=$(python -m site --user-base)/bin:$PATH
  pipenv run py.test --capture=no --ds=config.settings.test --flake8 .
